"""Initial database migration

Revision ID: aa3a502383be
Revises: 
Create Date: 2025-02-14 14:31:14.370106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa3a502383be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obituaries', sa.Column('obit_metadata', sa.JSON(), nullable=True))
    op.alter_column('obituaries', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('obituaries', 'generated_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index('idx_metadata', table_name='obituaries', postgresql_using='gin')
    op.drop_index('idx_metadata_gin', table_name='obituaries', postgresql_using='gin')
    op.drop_index('idx_metadata_name', table_name='obituaries', postgresql_using='gin')
    op.drop_index('idx_obit_text_gin', table_name='obituaries', postgresql_using='gin')
    op.create_index(op.f('ix_obituaries_id'), 'obituaries', ['id'], unique=False)
    op.drop_column('obituaries', 'created_at')
    op.drop_column('obituaries', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obituaries', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('obituaries', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_obituaries_id'), table_name='obituaries')
    op.create_index('idx_obit_text_gin', 'obituaries', ['generated_text'], unique=False, postgresql_using='gin')
    op.create_index('idx_metadata_name', 'obituaries', [sa.text("(metadata ->> 'name'::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_metadata_gin', 'obituaries', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_metadata', 'obituaries', ['metadata'], unique=False, postgresql_using='gin')
    op.alter_column('obituaries', 'generated_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('obituaries', 'input_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('obituaries', 'obit_metadata')
    # ### end Alembic commands ###
